spring:
  redis:
    #Redis服务器地址
    host: 127.0.0.1
    #Redis服务器端口号
    port: 6379
    #Redis数据库索引
    database: 0
    #连接超时时间，单位ms
    timeout: 1800000
    lettuce:
      pool:
        #连接池最大连接数，负值表示没有限制
        max-active: 20
        #连接池最大阻塞等待时间
        max-wait: -1
        #连接池最大空闲连接
        max-idle: 5
        #连接池最小空闲连接
        min-idle: 0